language:
  - php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script:
  - (cd "tests" ; ../vendor/bin/phpunit -c phpunit.xml --stop-on-failure)
  - vendor/bin/phpcs --standard=PSR2 src/ --ignore="*/test/*,autoload_classmap.php,*.js"
#  - vendor/bin/phpmd src text "codesize,naming" --exclude "*/test/*,*/autoload_classmap.php,*.js"
